name: living_city
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      # url: https://github.com/fusion44/flutter_map
      url: https://github.com/FilipeLarga/flutter_map
      ref: init-by-bounds
  geolocator: ^5.1.5
  flutter_bloc: ^2.1.1
  animations: ^1.0.0+5
  sliding_up_panel: ^1.0.1
  flutter_cupertino_date_picker: ^1.0.12
  sqflite: ^1.3.0
  path: ^1.6.4
  path_provider: ^1.6.10
  get_it: ^4.0.1
  shimmer: ^1.1.1
  http: ^0.12.1
  sembast: ^2.4.4+3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/category_icons/
    # - assets/delivery.png
    # - assets/landscape.jpg
    # - assets/distance_map.png
    # - assets/circle-cropped.png
    # - assets/2017-07-03_portugal_lisbon.mbtiles
    # - assets/tiles.mbtiles
    # - assets/map/10/484/ #10 484-486
    # - assets/map/10/485/
    # - assets/map/10/486/
    # - assets/map/11/969/ #11 969-973
    # - assets/map/11/970/
    # - assets/map/11/971/
    # - assets/map/11/972/
    # - assets/map/11/973/
    # - assets/map/12/1939/ #12 1939-1947
    # - assets/map/12/1940/
    # - assets/map/12/1941/
    # - assets/map/12/1942/
    # - assets/map/12/1943/
    # - assets/map/12/1944/
    # - assets/map/12/1945/
    # - assets/map/12/1946/
    # - assets/map/12/1947/
    # - assets/map/13/3878/ #13 3878-3894
    # - assets/map/13/3879/
    # - assets/map/13/3880/
    # - assets/map/13/3881/
    # - assets/map/13/3882/
    # - assets/map/13/3883/
    # - assets/map/13/3884/
    # - assets/map/13/3885/
    # - assets/map/13/3886/
    - assets/map/13/
    # - assets/map/13/3888/
    # - assets/map/13/3889/
    # - assets/map/13/3890/
    # - assets/map/13/3891/
    # - assets/map/13/3892/
    # - assets/map/13/3893/
    # - assets/map/13/3894/
    # - assets/map/14/7757/ #14 7757-7789
    # - assets/map/14/7758/
    # - assets/map/14/7759/
    # - assets/map/14/7760/
    # - assets/map/14/7761/
    # - assets/map/14/7762/
    # - assets/map/14/7763/
    # - assets/map/14/7764/
    # - assets/map/14/7765/
    # - assets/map/14/7766/
    # - assets/map/14/7767/
    # - assets/map/14/7768/
    # - assets/map/14/7769/
    # - assets/map/14/7770/
    # - assets/map/14/7771/
    # - assets/map/14/7772/
    # - assets/map/14/7773/
    # - assets/map/14/7774/
    - assets/map/14/7775/
    - assets/map/14/7776/
    # - assets/map/14/7777/
    # - assets/map/14/7778/
    # - assets/map/14/7779/
    # - assets/map/14/7780/
    # - assets/map/14/7781/
    # - assets/map/14/7782/
    # - assets/map/14/7783/
    # - assets/map/14/7784/
    # - assets/map/14/7785/
    # - assets/map/14/7786/
    # - assets/map/14/7787/
    # - assets/map/14/7788/
    # - assets/map/14/7789/
    # - assets/map/14/7789/
    - assets/map/15/15515/ #15 15515-15579
    - assets/map/15/15516/
    - assets/map/15/15517/
    - assets/map/15/15518/
    - assets/map/15/15519/
    - assets/map/15/15520/
    - assets/map/15/15521/
    - assets/map/15/15522/
    - assets/map/15/15523/
    - assets/map/15/15524/
    - assets/map/15/15525/
    - assets/map/15/15526/
    - assets/map/15/15527/
    - assets/map/15/15528/
    - assets/map/15/15529/
    - assets/map/15/15530/
    - assets/map/15/15531/
    - assets/map/15/15532/
    - assets/map/15/15533/
    - assets/map/15/15534/
    - assets/map/15/15535/
    - assets/map/15/15536/
    - assets/map/15/15537/
    - assets/map/15/15538/
    - assets/map/15/15539/
    - assets/map/15/15540/
    - assets/map/15/15541/
    - assets/map/15/15542/
    - assets/map/15/15543/
    - assets/map/15/15544/
    - assets/map/15/15545/
    - assets/map/15/15546/
    - assets/map/15/15547/
    - assets/map/15/15548/
    - assets/map/15/15549/
    - assets/map/15/15550/
    - assets/map/15/15551/
    - assets/map/15/15552/
    - assets/map/15/15553/
    - assets/map/15/15554/
    - assets/map/15/15555/
    - assets/map/15/15556/
    - assets/map/15/15557/
    - assets/map/15/15558/
    - assets/map/15/15559/
    - assets/map/15/15560/
    - assets/map/15/15561/
    - assets/map/15/15562/
    - assets/map/15/15563/
    - assets/map/15/15564/
    - assets/map/15/15565/
    - assets/map/15/15566/
    - assets/map/15/15567/
    - assets/map/15/15568/
    - assets/map/15/15569/
    - assets/map/15/15570/
    - assets/map/15/15571/
    - assets/map/15/15572/
    - assets/map/15/15573/
    - assets/map/15/15574/
    - assets/map/15/15575/
    - assets/map/15/15576/
    - assets/map/15/15577/
    - assets/map/15/15578/
    - assets/map/15/15579/
    # - assets/map/16/31030/
    # - assets/map/16/31031/
    # - assets/map/16/31032/
    # - assets/map/16/31033/
    # - assets/map/16/31034/
    # - assets/map/16/31035/
    # - assets/map/16/31036/
    # - assets/map/16/31037/
    # - assets/map/16/31038/
    # - assets/map/16/31039/
    # - assets/map/16/31040/
    # - assets/map/16/31041/
    # - assets/map/16/31042/
    # - assets/map/16/31043/
    # - assets/map/16/31044/
    # - assets/map/16/31045/
    # - assets/map/16/31046/
    # - assets/map/16/31047/
    # - assets/map/16/31048/
    # - assets/map/16/31049/
    # - assets/map/16/31050/
    # - assets/map/16/31051/
    # - assets/map/16/31052/
    # - assets/map/16/31053/
    # - assets/map/16/31054/
    # - assets/map/16/31055/
    # - assets/map/16/31056/
    # - assets/map/16/31057/
    # - assets/map/16/31058/
    # - assets/map/16/31059/
    # - assets/map/16/31060/
    # - assets/map/16/31061/
    # - assets/map/16/31062/
    # - assets/map/16/31063/
    # - assets/map/16/31064/
    # - assets/map/16/31065/
    # - assets/map/16/31066/
    # - assets/map/16/31067/
    # - assets/map/16/31068/
    # - assets/map/16/31069/
    # - assets/map/16/31070/
    # - assets/map/16/31071/
    # - assets/map/16/31072/
    # - assets/map/16/31073/
    # - assets/map/16/31074/
    # - assets/map/16/31075/
    # - assets/map/16/31076/
    # - assets/map/16/31077/
    # - assets/map/16/31078/
    # - assets/map/16/31079/
    # - assets/map/16/31080/
    # - assets/map/16/31081/
    # - assets/map/16/31082/
    # - assets/map/16/31083/
    # - assets/map/16/31084/
    # - assets/map/16/31085/
    # - assets/map/16/31086/
    # - assets/map/16/31087/
    # - assets/map/16/31088/
    # - assets/map/16/31089/
    # - assets/map/16/31090/
    # - assets/map/16/31091/
    # - assets/map/16/31092/
    # - assets/map/16/31093/
    # - assets/map/16/31094/
    # - assets/map/16/31095/
    # - assets/map/16/31096/
    # - assets/map/16/31097/
    # - assets/map/16/31098/
    # - assets/map/16/31099/
    # - assets/map/16/31100/
    # - assets/map/16/31101/
    # - assets/map/16/31102/
    # - assets/map/16/31103/
    # - assets/map/16/31104/
    # - assets/map/16/31105/
    # - assets/map/16/31106/
    # - assets/map/16/31107/
    # - assets/map/16/31108/
    # - assets/map/16/31109/
    # - assets/map/16/31110/
    # - assets/map/16/31111/
    # - assets/map/16/31112/
    # - assets/map/16/31113/
    # - assets/map/16/31114/
    # - assets/map/16/31115/
    # - assets/map/16/31116/
    # - assets/map/16/31117/
    # - assets/map/16/31118/
    # - assets/map/16/31119/
    # - assets/map/16/31120/
    # - assets/map/16/31121/
    # - assets/map/16/31122/
    # - assets/map/16/31123/
    # - assets/map/16/31124/
    # - assets/map/16/31125/
    # - assets/map/16/31126/
    # - assets/map/16/31127/
    # - assets/map/16/31128/
    # - assets/map/16/31129/
    # - assets/map/16/31130/
    # - assets/map/16/31131/
    # - assets/map/16/31132/
    # - assets/map/16/31133/
    # - assets/map/16/31134/
    # - assets/map/16/31135/
    # - assets/map/16/31136/
    # - assets/map/16/31137/
    # - assets/map/16/31138/
    # - assets/map/16/31139/
    # - assets/map/16/31140/
    # - assets/map/16/31141/
    # - assets/map/16/31142/
    # - assets/map/16/31143/
    # - assets/map/16/31144/
    # - assets/map/16/31145/
    # - assets/map/16/31146/
    # - assets/map/16/31147/
    # - assets/map/16/31148/
    # - assets/map/16/31149/
    # - assets/map/16/31150/
    # - assets/map/16/31151/
    # - assets/map/16/31152/
    # - assets/map/16/31153/
    # - assets/map/16/31154/
    # - assets/map/16/31155/
    # - assets/map/16/31156/
    # - assets/map/16/31157/





# An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Opensans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
